
#Mekanism Additions Common Config. This config is not sync'd between server and client.
[additions-common]

	#Config options regarding spawning of entities.
	[additions-common.spawning]

		#Config options regarding baby endermen.
		[additions-common.spawning.baby-endermen]
			#The list of biome ids that baby endermen will not spawn in even if the normal mob variant can spawn.
			biomeBlackList = []
			#The multiplier for max spawn cost of baby endermen spawns, compared to the adult mob.
			#Range: 0.0 ~ 100.0
			maxSpawnCostPercentage = 1.0
			#The multiplier for maximum group size of baby endermen spawns, compared to the adult mob.
			#Range: 0.0 ~ 100.0
			maxSizePercentage = 0.5
			#The multiplier for spawn cost per entity of baby endermen spawns, compared to the adult mob.
			#Range: 0.0 ~ 100.0
			spawnCostPerEntityPercentage = 1.0
			#The multiplier for minimum group size of baby endermen spawns, compared to the adult mob.
			#Range: 0.0 ~ 100.0
			minSizePercentage = 0.5
			#The multiplier for weight of baby endermen spawns, compared to the adult mob.
			#Range: 0.0 ~ 100.0
			weightPercentage = 0.5
			#Enable the spawning of baby endermen. Think baby zombies.
			shouldSpawn = false
			#The list of structure ids that baby endermen will not spawn in even if the normal mob variant can spawn.
			structureBlackList = []

		#Config options regarding baby creepers.
		[additions-common.spawning.baby-creepers]
			#The list of biome ids that baby creepers will not spawn in even if the normal mob variant can spawn.
			biomeBlackList = []
			#The multiplier for max spawn cost of baby creepers spawns, compared to the adult mob.
			#Range: 0.0 ~ 100.0
			maxSpawnCostPercentage = 1.0
			#The multiplier for maximum group size of baby creepers spawns, compared to the adult mob.
			#Range: 0.0 ~ 100.0
			maxSizePercentage = 0.5
			#The multiplier for spawn cost per entity of baby creepers spawns, compared to the adult mob.
			#Range: 0.0 ~ 100.0
			spawnCostPerEntityPercentage = 1.0
			#The multiplier for minimum group size of baby creepers spawns, compared to the adult mob.
			#Range: 0.0 ~ 100.0
			minSizePercentage = 0.5
			#The multiplier for weight of baby creepers spawns, compared to the adult mob.
			#Range: 0.0 ~ 100.0
			weightPercentage = 0.5
			#Enable the spawning of baby creepers. Think baby zombies.
			shouldSpawn = false
			#The list of structure ids that baby creepers will not spawn in even if the normal mob variant can spawn.
			structureBlackList = []

		#Config options regarding baby wither skeletons.
		[additions-common.spawning.baby-wither-skeletons]
			#The list of biome ids that baby wither skeletons will not spawn in even if the normal mob variant can spawn.
			biomeBlackList = []
			#The multiplier for max spawn cost of baby wither skeletons spawns, compared to the adult mob.
			#Range: 0.0 ~ 100.0
			maxSpawnCostPercentage = 1.0
			#The multiplier for maximum group size of baby wither skeletons spawns, compared to the adult mob.
			#Range: 0.0 ~ 100.0
			maxSizePercentage = 0.5
			#The multiplier for spawn cost per entity of baby wither skeletons spawns, compared to the adult mob.
			#Range: 0.0 ~ 100.0
			spawnCostPerEntityPercentage = 1.0
			#The multiplier for minimum group size of baby wither skeletons spawns, compared to the adult mob.
			#Range: 0.0 ~ 100.0
			minSizePercentage = 0.5
			#The multiplier for weight of baby wither skeletons spawns, compared to the adult mob.
			#Range: 0.0 ~ 100.0
			weightPercentage = 0.5
			#Enable the spawning of baby wither skeletons. Think baby zombies.
			shouldSpawn = false
			#The list of structure ids that baby wither skeletons will not spawn in even if the normal mob variant can spawn.
			structureBlackList = []

		#Config options regarding baby skeletons.
		[additions-common.spawning.baby-skeletons]
			#The list of biome ids that baby skeletons will not spawn in even if the normal mob variant can spawn.
			biomeBlackList = []
			#The multiplier for max spawn cost of baby skeletons spawns, compared to the adult mob.
			#Range: 0.0 ~ 100.0
			maxSpawnCostPercentage = 1.0
			#The multiplier for maximum group size of baby skeletons spawns, compared to the adult mob.
			#Range: 0.0 ~ 100.0
			maxSizePercentage = 0.5
			#The multiplier for spawn cost per entity of baby skeletons spawns, compared to the adult mob.
			#Range: 0.0 ~ 100.0
			spawnCostPerEntityPercentage = 1.0
			#The multiplier for minimum group size of baby skeletons spawns, compared to the adult mob.
			#Range: 0.0 ~ 100.0
			minSizePercentage = 0.5
			#The multiplier for weight of baby skeletons spawns, compared to the adult mob.
			#Range: 0.0 ~ 100.0
			weightPercentage = 0.5
			#Enable the spawning of baby skeletons. Think baby zombies.
			shouldSpawn = false
			#The list of structure ids that baby skeletons will not spawn in even if the normal mob variant can spawn.
			structureBlackList = []

		#Config options regarding baby strays.
		[additions-common.spawning.baby-strays]
			#The list of biome ids that baby strays will not spawn in even if the normal mob variant can spawn.
			biomeBlackList = []
			#The multiplier for max spawn cost of baby strays spawns, compared to the adult mob.
			#Range: 0.0 ~ 100.0
			maxSpawnCostPercentage = 1.0
			#The multiplier for maximum group size of baby strays spawns, compared to the adult mob.
			#Range: 0.0 ~ 100.0
			maxSizePercentage = 0.5
			#The multiplier for spawn cost per entity of baby strays spawns, compared to the adult mob.
			#Range: 0.0 ~ 100.0
			spawnCostPerEntityPercentage = 1.0
			#The multiplier for minimum group size of baby strays spawns, compared to the adult mob.
			#Range: 0.0 ~ 100.0
			minSizePercentage = 0.5
			#The multiplier for weight of baby strays spawns, compared to the adult mob.
			#Range: 0.0 ~ 100.0
			weightPercentage = 0.5
			#Enable the spawning of baby strays. Think baby zombies.
			shouldSpawn = false
			#The list of structure ids that baby strays will not spawn in even if the normal mob variant can spawn.
			structureBlackList = []

