#
#Tier Creative Apiary Output
#Allowed Values: BLOCK
tierCreativeApiaryOutput = "BLOCK"
#
#Tier Creative Apiary Quantity 
# How many Combs/Blocks per Bees?
#Range: > 1
tierCreativeApiaryQuantity = 15
#
#Tier Creative Apiary Max Bees
#Range: > 1
tierCreativeApiaryMaxBees = 18
#
#Tier Creative Apiary Max Time in Hive (Value in %) 
#For example 0.7 = 70% reduction
#Range: 0.0 ~ 1.0
tierCreativeApiaryMaxTimeInHive = 0.85

