[tweaks]
	enableButtons = 0

#Sorting customization
[sorting]
	#Custom settings per GUI
	#x = x-position of external sort button relative to GUI top left
	#y = same as above except for the y-position
	#Omit x and y to leave position unchanged
	#sortRange = slots to sort
	#E.g. sortRange = "5,0-2" sorts slots 5,0,1,2 in that order
	#sortRange = "" disables sorting for that container
	#Out-of-bound slots are ignored
	#Omit sortRange to leave as default
	[[sorting.containerOverrides]]
		containerClass = "com.tfar.craftingstation.CraftingStationContainer"
		sortRange = ""

	[[sorting.containerOverrides]]
		containerClass = "tfar.dankstorage.container.DankContainers"
		sortRange = ""

	[[sorting.containerOverrides]]
		containerClass = "mcjty.rftoolsutility.modules.crafter.blocks.CrafterContainer"
		sortRange = ""

	[[sorting.containerOverrides]]
		containerClass = "appeng.container.implementations.InterfaceTerminalContainer"
		sortRange = ""

	[[sorting.containerOverrides]]
		containerClass = "appeng.container.implementations.CraftingTermContainer"
		sortRange = ""

	[[sorting.containerOverrides]]
		containerClass = "appeng.container.implementations.PatternTermContainer"
		sortRange = ""

	[[sorting.containerOverrides]]
		containerClass = "appeng.container.implementations.WirelessTermContainer"
		sortRange = ""

	[[sorting.containerOverrides]]
		containerClass = "com.YTrollman.CreativeCrafter.container.CreativeCrafterContainerMenu"
		sortRange = ""

	[[sorting.containerOverrides]]
		containerClass = "edivad.extrastorage.container.AdvancedCrafterContainer"
		sortRange = ""

	[[sorting.containerOverrides]]
		containerClass = "com.refinedmods.refinedstorage.container.CrafterContainer"
		sortRange = ""

	[[sorting.containerOverrides]]
		containerClass = "com.refinedmods.refinedstorage.container.CrafterManagerContainer"
		sortRange = ""

	[[sorting.containerOverrides]]
		containerClass = "slimeknights.tconstruct.smeltery.inventory.HeatingStructureContainer"
		sortRange = ""
